name: Build and Push FEX Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Runtime metadata
        id: meta-runtime
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract Docker Installer metadata
        id: meta-installer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-installer

      - name: Build and push Docker Runtime image
        uses: docker/build-push-action@v5
        with:
          context: Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta-runtime.outputs.tags }}
          labels: ${{ steps.meta-runtime.outputs.labels }}
          # This cache speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Docker Install image
        uses: docker/build-push-action@v5
        with:
          context: Dockerfile.install
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta-installer.outputs.tags }}
          labels: ${{ steps.meta-installer.outputs.labels }}
          # This cache speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
